services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.9.0-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The vhost and conf volumes are only required
      # if you plan to obtain standalone certificates
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion:2.6.2
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=admin@example.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  climb-buddy:
    image: climb-buddy:v0.0.1
    container_name: climb-buddy
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=admin@example.io
    volumes:
      - ./data.db:/app/data.db

networks:
  default:
      name: nginx-proxy-net

volumes:
  vhost:
  conf:
  html:
  certs:
  acme: